logging:
  level:
    org:
      hibernate:
        SQL: INFO
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 1200000
      maximum-pool-size: 5
      minimum-idle: 2
      pool-name: data-source
    url: jdbc:mysql://localhost:8989/escuela?useSSL=false&useUnicode=yes&characterEncoding=UTF-8
    password: root
    username: root
  jackson:
    date-format: MMMM dd yyyy / HH:mm
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
springdoc:
  api-docs:
    path: /docs/v3/api-docs
  swagger-ui:
    path: /docs/swagger-ui